
language: node_js
node_js:
  - "14"

branches:
  only:
    - main

script:
  - echo "Omitiendo tests"

cache:
  directories:
    - ./node_modules

before_deploy:
  - cd client
  - npm install
  - npm run build
  - cp static.json dist/static.json
  - cd dist

deploy:
  provider: heroku
  skip_cleanup: true
  keep_history: true
  api_key: $HEROKU_KEY
  app: restaurante-donboloensusalsa
  on:
    branch: main
