# Generated by Django 3.2.4 on 2021-09-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fechaReserva',
            field=models.CharField(max_length=20),
        ),
    ]
