# Generated by Django 3.2.4 on 2021-07-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
